Chef 15 compatibility
osuosl-cookbooks/osl-letsencrypt-boulder-server pull request #13
Opened 2020-06-16 22:08 UTC by detjensrobert

Idempotency has been disabled for this cookbook as `yum_version_lock` and the `ruby_block` resources run on every converge.

2020-06-16 22:10 UTC, detjensrobert commented
![](https://github.trello.services/images/mini-trello-icon.png) [Chef 15 compatibility fixes](https://trello.com/c/k2lpIE2U/1570-chef-15-compatibility-fixes)

2020-06-16 22:10 UTC, detjensrobert commented
![](https://github.trello.services/images/mini-trello-icon.png) [Chef 15 compatibility fixes](https://trello.com/c/k2lpIE2U/1570-chef-15-compatibility-fixes)

2020-06-18 16:44 UTC, ramereth requested changes
Can you please create a new issue on this cookbook to deal with refactoring the ``ruby_block`` resources into libraries/resources so we can properly have some idempotency with this cookbook.

2020-06-18 16:44 UTC, ramereth commented on Berksfile
> +cookbook 'osl-selinux', git: 'git@github.com:osuosl-cookbooks/osl-selinux', branch: 'ramereth/chef15'
This was merged so you can remove the branch spec.

2020-06-18 16:44 UTC, ramereth commented on Berksfile
> +cookbook 'firewall', git: 'git@github.com:osuosl-cookbooks/firewall', branch: 'ramereth/chef15'
This was merged so you can remove the branch spec.

2020-06-18 16:44 UTC, ramereth commented on Berksfile
> +cookbook 'osl-rsync', git: 'git@github.com:osuosl-cookbooks/osl-rsync', branch: 'ramereth/chef15'
This was merged so you can remove the branch spec.

2020-06-18 16:44 UTC, ramereth commented on kitchen.yml
> +  multiple_converge: 2
Please comment this out and leave a message why.

2020-06-18 16:44 UTC, ramereth commented on metadata.rb
> +chef_version     '>= 12.18'
Looks like this got missed on a previous update.
```suggestion
chef_version     '>= 14'
```

2020-06-19 01:04 UTC, detjensrobert commented
`ruby_block` removal PR: https://github.com/osuosl-cookbooks/osl-letsencrypt-boulder-server/pull/14

2020-06-19 15:42 UTC, ramereth commented
![](https://github.trello.services/images/mini-trello-icon.png) [Chef 15: osl-letsencrypt-boulder-server](https://trello.com/c/JewZuxTp/1758-chef-15-osl-letsencrypt-boulder-server)

2020-06-23 21:58 UTC, ramereth commented on Berksfile
> +cookbook 'osl-nrpe', git: 'git@github.com:osuosl-cookbooks/osl-nrpe', branch: 'ramereth/chef15'
These three were merged so you can update these now. Same for osl-php.

2020-06-24 16:22 UTC, ramereth commented on Berksfile
> +cookbook 'osl-acme', git: 'git@github.com:osuosl-cookbooks/osl-acme
```suggestion
cookbook 'osl-acme', git: 'git@github.com:osuosl-cookbooks/osl-acme'
```

2020-06-24 21:30 UTC, ramereth commented on Berksfile
> +cookbook 'osl-docker', git: 'git@github.com:osuosl-cookbooks/osl-docker', branch: 'detjensrobert/chef15'
Now you need to remove this branch reference :laughing:

2020-06-24 21:43 UTC, ramereth approved these changes
Please do a minor bump.

2020-06-24 21:45 UTC, detjensrobert commented
!bump minor *

2020-06-24 21:46 UTC, merged

2020-06-24 21:46 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v3.2.0.  Have a nice day!